x-service-templates:
  api-template: &api-template
    build: ./api
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy

services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

  loadbalancer:
    image: nginx:1.29.0-alpine
    container_name: loadbalancer
    ports:
      - 9999:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '40MB'

  api1:
    <<: *api-template
    container_name: api1
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'

  api2:
    <<: *api-template
    container_name: api2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'

  worker:
    build: ./worker
    container_name: worker
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

networks:
  payment-processor:
    external: true
  backend:
    driver: bridge
